### ISSUE TITLE
Player Character does not spawn in with mod enabled.

### ISSUE THREAD

**Issue by heGits** [Nebby1999/VarianceAPI#1]
This mod combined with your other recent mods, TheOriginal30 and NebbysWrath, prevent the player from spawning in the first stage. This issue is resolved when I disable these mods.

These are a few screenshots of the camera upon the beginning of a new game. They will always start at these location.

![Risk of Rain 2 Screenshot 2021 06 16 - 09 44 06 36](https://user-images.githubusercontent.com/81045665/122240873-b6efae80-ce87-11eb-8fee-e3b423f2b950.png)
![Risk of Rain 2 Screenshot 2021 06 16 - 09 44 24 97](https://user-images.githubusercontent.com/81045665/122240885-b9520880-ce87-11eb-87da-e1fb318073b7.png)
![Risk of Rain 2 Screenshot 2021 06 16 - 09 43 48 100](https://user-images.githubusercontent.com/81045665/122240863-b525eb00-ce87-11eb-9dd5-b2eecc78963f.png)

I used the older Variant mods before these and have uninstalled them in favor of these more recent mods.

This is all of the info that I have for this issue. I hope you find this useful and I hope it can be resolved.

**Comment by PRMoffatt** [comment]
I have the same issue - updated from the old variant mods, can't spawn at the start of stages any more

**Comment by RoR2TeamRogue** [comment]
Send the log of these issues. if by any chance you had Wonda's Refightilization mod, then it was a known bug that's now fixed on their side.

Updating Refightilization should fix said issue.

**Comment by Nebby1999** [comment]
Send the full log if possible so i can do a proper log check and see for any incompatibilities.

Now, if this bug was caused while having Wonda's Refightilization mod installed, it's a bug that was known and that i fixed from Wonda's side of things. updating Refightilization should fix this issue.

**Comment by heGits** [comment]
Sorry, it's been so long since then. The problem has been resolved for me
and should not be worried about.

**Comment by Nebby1999** [comment]
i will close this issue for now.
