### ISSUE TITLE
Bug: NRE Error Spam

### ISSUE THREAD

**Issue by cobaltw** [Nebby1999/VarianceAPI#10]
When using any variants the console is near constantly spammed with NullReferenceExceptions. I've determined that it's an API issue, as it happens regardless of which variant mod is used. It seems to happen on every Update.
This is not a compatibility issue, as I've tested using only the API and a variant pack. I've tested using TheOriginal30 and HIFUVariants separately.
It doesn't seem to have an impact in game that I've noticed, but it is problematic regardless since you can't read anything in the console while this happens, and after finishing a run there can be hundreds of thousands of errors (I've even hit over one million).

Below is a copy of the error thrown. Every error is identical from what I can tell.
> [Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
VarianceAPI.Components.VariantHandler.ReplaceSkill (VarianceAPI.ScriptableObjects.VariantInfo variantInfo) (at <eb16b0129925472aa4a66da3ab41b6eb>:IL_00EE)
VarianceAPI.Components.VariantHandler.Modify () (at <eb16b0129925472aa4a66da3ab41b6eb>:IL_011F)
VarianceAPI.Components.VariantSpawnHandler.RpcModifyComponents (System.Int32[] indexes, VarianceAPI.Components.VariantSpawnHandler+RPCVariantInfo variantInfoSearchType) (at <eb16b0129925472aa4a66da3ab41b6eb>:IL_00B9)
VarianceAPI.Components.VariantSpawnHandler.InvokeRpcRpcModifyComponents (UnityEngine.Networking.NetworkBehaviour obj, UnityEngine.Networking.NetworkReader reader) (at <eb16b0129925472aa4a66da3ab41b6eb>:IL_0028)
UnityEngine.Networking.NetworkIdentity.HandleRPC (System.Int32 cmdHash, UnityEngine.Networking.NetworkReader reader) (at <73dce905efe04cb5acf013e51496d921>:IL_0116)
UnityEngine.Networking.ClientScene.OnRPCMessage (UnityEngine.Networking.NetworkMessage netMsg) (at <73dce905efe04cb5acf013e51496d921>:IL_0060)
UnityEngine.Networking.NetworkConnection.InvokeHandler (UnityEngine.Networking.NetworkMessage netMsg) (at <73dce905efe04cb5acf013e51496d921>:IL_0024)
UnityEngine.Networking.LocalClient.ProcessInternalMessages () (at <73dce905efe04cb5acf013e51496d921>:IL_00B9)
UnityEngine.Networking.LocalClient.Update () (at <73dce905efe04cb5acf013e51496d921>:IL_0000)
UnityEngine.Networking.NetworkClient.UpdateClients () (at <73dce905efe04cb5acf013e51496d921>:IL_001C)
UnityEngine.Networking.NetworkIdentity.UNetStaticUpdate () (at <73dce905efe04cb5acf013e51496d921>:IL_0005)

**Comment by Nebby1999** [comment]
2 things of note:

Please provide a log
Please provide a copy of your modded setup either via a code or a file (file is preferred)

**Comment by cobaltw** [comment]
Well, this is embarrassing, but I've realized the problem was just that I had turned FixPluginTypesSerialization while trying to figure out what was causing a _different_ NRE on update without realizing that VarianceAPI depends on it. My initial issue turns out to be caused by HIFUVariants, unrelated to the API itself. Sorry for the false alarm.

**Comment by Nebby1999** [comment]
I suspected as much to be fair, the system works allright and it can usually be caused by poorly implementing a skill replacement. also, don't worry about the false alarm, i've already informed HIFU about the situation
