### ISSUE TITLE
VAPI Conflicting With Other Mods

### ISSUE THREAD

**Issue by Scrublord1337** [Nebby1999/VarianceAPI#11]
HI Nebby, I've noticed that VAPI seems to generating some errors. I could be wrong but it seems to be conflicting with Void Heart from Aetherium, I assume when a player has it in their inventory. There are a handful of other errors throughout the log that may noteworthy to you.
[VAPI Conflicts.txt](https://github.com/Nebby1999/VarianceAPI/files/7851785/VAPI.Conflicts.txt)

**Comment by Nebby1999** [comment]
Outdated
