### ISSUE TITLE
Some Variants Drop 0 Gold (and maybe 0 XP?)

### ISSUE THREAD

**Issue by drp527** [Nebby1999/VarianceAPI#14]
I've noticed that some variants fairly consistently give no money even on default settings for rewards. The most easily seen for me are Beetle-family variants (including Guards) and Bison in Siphoned Forest, but it seems to persist most of the time even on later stages. 
[LogOutput.log](https://github.com/Nebby1999/VarianceAPI/files/10367866/LogOutput.log)

**Comment by Nebby1999** [comment]
this has been patched now, it'll be released as soon as possible
