### ISSUE TITLE
Possible Enhancement: Give VariantSpawnCondition a delegate bool version of IsAvailable()

### ISSUE THREAD

**Issue by RicoValdezio** [Nebby1999/VarianceAPI#16]
Probably an incredibly niche use case for this, but allowing variant pack creators to define their own boolean delegate for whether or not a spawn criteria has been met would allow for more creativity in how and when variants are able to spawn. This would be especially true for variant packs that have their own separate dependencies, as they could use their own flags to determine/influence when a variant spawns without having to overwrite/intercept the IsAvailable call or deny/remove the variant from the pool in their specific exclude cases.

**Comment by Nebby1999** [comment]
Would you be kind to explain some more use cases? VariantSpawnCondition's methods are already virtual so anyone making a variant pack could make an extended version with more spawning criteria, the only thing I can think about it is for mods that interact with external packs to modify spawns

I'd even wager you're asking for this for some cross compat for Genetics, if so i can add it

**Comment by RicoValdezio** [comment]
My bad, I completely missed the virtual keyword on my first read-through. Wasn't planning on using it myself, but if I do I'll just stand up a derived class and overwrite what I need.
