### ISSUE TITLE
Enhancement: Add Count, Elite index, Ally index and AI Braindead to spawn_variant command - just like in DebugToolkit's spawn_ai command

### ISSUE THREAD

**Issue by hifoomin** [Nebby1999/VarianceAPI#7]

**Comment by Nebby1999** [comment]
if you could provide some examples this would be great hifu, but this will probably be added on VarianceAPI 1.2, which is still a bit far away due to next major release chopping the deprecated classes and replacing certain modules and whatnot with MSU ones.
