### ISSUE TITLE
Enhancement: Add Health Per Level Multiplier to VariantInfo

### ISSUE THREAD

**Issue by hifoomin** [Nebby1999/VarianceAPI#8]
This would enable more fine-tuned balance and facilitate the use of items such as Helfire Tincture and Fuel Array.

Alternatively, just make Health Per Level be 30% of the Base Max Health in the VariantHandler class

**Comment by Nebby1999** [comment]
I have an idea on how to make the stat modifiers a lot more modifiable (idea came to mind when working on a scriptable object on ss2 for spawning the boss version of nemesis commando). but sadly whenever i get to do this will take a bit of time.
